FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache bash

RUN apk add --no-cache curl

# Install air for live reload
RUN go install github.com/air-verse/air@latest

# Install swag for OpenAPI doc generation
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air"]
